packages:
  # Deployable applications
  - 'apps/*'

  # Core infrastructure libraries
  - 'libs/workflow-engine'
  - 'libs/database'
  - 'libs/shared/types'
  - 'libs/shared/validation'
  - 'libs/shared/utils'
  - 'libs/shared/configs'
  - 'libs/ui'

  # Business capability modules
  - 'modules/workflows'
  - 'modules/market-roles/*'
  - 'modules/integrations/*'

  # Optional/custom functionality
  - 'extensions/*'

  # Development utilities
  - 'tools/*'
